# golangci-lint configuration file
version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  cyclop:
    max-complexity: 25  # 调整复杂度限制以允许更复杂的函数
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  govet:
    # check-shadowing is deprecated, use shadow linter instead
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  unused:
    check-exported: false
    
  revive:
    min-confidence: 0.8
    
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive
    - cyclop
    - goconst
    - nakedret

issues:
  exclude-dirs:
    - vendor
    - tmp
  exclude-files:
    - ".*\\.pb\\.go$"
  uniq-by-line: true
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - errcheck
        - revive
        - goconst
        - staticcheck
    
    - path: cmd/main\.go
      linters:
        - cyclop
        - revive
        - errcheck
    
    - path: tmp/
      linters:
        - cyclop
        - errcheck
        - revive
        - goconst
        - staticcheck
        
    # 排除一些常见的false positive
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - revive
    
    - text: "error strings should not be capitalized"
      linters:
        - staticcheck
    
    - text: "has been deprecated since Go"
      linters:
        - staticcheck
        
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false